import type { MemberSimple } from "@features/members";
import type { ClosureType, ScheduleDay, Shift, SlotStatus } from "../constants";

export interface SlotTag {
  id: string;
  name: string;
  colorHex?: string | null;
}

export interface TimeSlot {
  id: string;
  dayOfWeek: ScheduleDay;
  startTime: string;
  capacity: number;
  enabled: boolean;
  tag?: SlotTag | null;
}

export interface MemberTurn {
  id: string;
  timeSlotId: string;
  member: MemberSimple;
  startDate: string;
  endDate?: string | null;
  isActive: boolean;
  heldByOwner: boolean;
}

export interface CalendarClosure {
  id: string;
  type: ClosureType;
  startDate: string;
  endDate: string;
  reason?: string | null;
  isAutoGenerated?: boolean;
}

export interface TimeSlotOverride {
  id: string;
  timeSlotId: string;
  date: string;
  reason?: string | null;
}

export interface ScheduleDayInfo {
  date: string;
  dayOfWeek: ScheduleDay;
  closure?: CalendarClosure | null;
}

export interface ScheduleWeek {
  from: string;
  to: string;
  days: ScheduleDayInfo[];
  timeSlots: TimeSlot[];
  turns: MemberTurn[];
  overrides: TimeSlotOverride[];
}

export interface SlotRosterEntry {
  turn: MemberTurn;
  isOverturn: boolean;
}

interface BaseCell {
  id: string;
  date: string;
  dayOfWeek: ScheduleDay;
  startTime: string;
}

export interface SlotCellData extends BaseCell {
  kind: "slot";
  slot: TimeSlot;
  roster: SlotRosterEntry[];
  status: SlotStatus;
}

export interface BlockCellData extends BaseCell {
  kind: "block";
  slot: TimeSlot;
}

export interface DisabledCellData extends BaseCell {
  kind: "disabled";
  slot: TimeSlot;
}

export interface ClosedCellData extends BaseCell {
  kind: "closed";
  slot: TimeSlot;
  closure: CalendarClosure;
}

export interface BlockedCellData extends BaseCell {
  kind: "blocked";
  slot: TimeSlot;
  override: TimeSlotOverride;
}

export interface UnavailableCellData extends BaseCell {
  kind: "unavailable";
}

export type ScheduleCellData =
  | SlotCellData
  | BlockCellData
  | DisabledCellData
  | ClosedCellData
  | BlockedCellData
  | UnavailableCellData;

export interface ScheduleRow {
  startTime: string;
  endTime: string;
  shift: Shift;
  cells: ScheduleCellData[];
}

export interface ScheduleGrid {
  days: ScheduleDayInfo[];
  rows: ScheduleRow[];
}

export interface AssignTurnDto {
  timeSlotId: string;
  memberId: string;
}

export interface MoveTurnDto {
  timeSlotId: string;
}

export interface SetTurnHoldDto {
  heldByOwner: boolean;
}

export interface CreateTimeSlotDto {
  startTime: string;
  capacity: number;
}

export interface UpdateTimeSlotDto {
  capacity?: number;
  enabled?: boolean;
  tagId?: string | null;
}

export interface CreateClosureDto {
  type: ClosureType;
  startDate: string;
  endDate: string;
  reason?: string;
}

export interface CreateOverrideDto {
  timeSlotId: string;
  date: string;
  reason?: string;
}
