/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AttendanceRouteImport } from './routes/_attendance'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTrainingPlansRouteImport } from './routes/_authenticated/training-plans'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedInstructorsRouteImport } from './routes/_authenticated/instructors'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAttendancesRouteImport } from './routes/_authenticated/attendances'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AttendanceAttendanceRouteImport } from './routes/_attendance/attendance'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/_authenticated/members/index'
import { Route as AuthenticatedInstructorsIndexRouteImport } from './routes/_authenticated/instructors/index'
import { Route as AuthenticatedAttendancesIndexRouteImport } from './routes/_authenticated/attendances/index'
import { Route as AuthenticatedTrainingPlansRegisterRouteImport } from './routes/_authenticated/training-plans_.register'
import { Route as AuthenticatedMembersRegisterRouteImport } from './routes/_authenticated/members_.register'
import { Route as AuthenticatedExercisesRegisterRouteImport } from './routes/_authenticated/exercises_.register'
import { Route as AuthenticatedExercisesGroupIdRouteImport } from './routes/_authenticated/exercises_.$groupId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/_admin/users'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/_admin/settings'
import { Route as AuthenticatedAdminMembershipsRouteImport } from './routes/_authenticated/_admin/memberships'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/_admin/audit'
import { Route as AuthenticatedAdminSettingsIndexRouteImport } from './routes/_authenticated/_admin/settings/index'
import { Route as AuthenticatedTrainingPlansEditTrainingPlanIdRouteImport } from './routes/_authenticated/training-plans_.edit.$trainingPlanId'
import { Route as AuthenticatedMembersUpdateMemberIdRouteImport } from './routes/_authenticated/members_.update.$memberId'
import { Route as AuthenticatedMembersRegisterClinicalProfileRouteImport } from './routes/_authenticated/members_.register_.clinical-profile'
import { Route as AuthenticatedMembersProfileMemberIdRouteImport } from './routes/_authenticated/members_.profile.$memberId'
import { Route as AuthenticatedMembersMemberIdClinicalProfileRouteImport } from './routes/_authenticated/members_.$memberId.clinical-profile'
import { Route as AuthenticatedAdminSettingsRiskFlagsRouteImport } from './routes/_authenticated/_admin/settings/risk-flags'
import { Route as AuthenticatedAdminSettingsParametersRouteImport } from './routes/_authenticated/_admin/settings/parameters'
import { Route as AuthenticatedAdminSettingsGroupExercisesRouteImport } from './routes/_authenticated/_admin/settings/group-exercises'
import { Route as AuthenticatedExercisesGroupIdUpdateExerciseIdRouteImport } from './routes/_authenticated/exercises_.$groupId_.update.$exerciseId'
import { Route as AuthenticatedExercisesGroupIdProfileExerciseIdRouteImport } from './routes/_authenticated/exercises_.$groupId_.profile.$exerciseId'
import { Route as AuthenticatedAdminSettingsRiskFlagsRegisterRouteImport } from './routes/_authenticated/_admin/settings/risk-flags_.register'
import { Route as AuthenticatedAdminSettingsGroupExercisesRegisterRouteImport } from './routes/_authenticated/_admin/settings/group-exercises_.register'
import { Route as AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRouteImport } from './routes/_authenticated/_admin/settings/risk-flags_.update.$riskFlagId'
import { Route as AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRouteImport } from './routes/_authenticated/_admin/settings/group-exercises_.update.$groupExerciseId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/_attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrainingPlansRoute =
  AuthenticatedTrainingPlansRouteImport.update({
    id: '/training-plans',
    path: '/training-plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInstructorsRoute =
  AuthenticatedInstructorsRouteImport.update({
    id: '/instructors',
    path: '/instructors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAttendancesRoute =
  AuthenticatedAttendancesRouteImport.update({
    id: '/attendances',
    path: '/attendances',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AttendanceAttendanceRoute = AttendanceAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AttendanceRoute,
} as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMembersRoute,
  } as any)
const AuthenticatedInstructorsIndexRoute =
  AuthenticatedInstructorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInstructorsRoute,
  } as any)
const AuthenticatedAttendancesIndexRoute =
  AuthenticatedAttendancesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAttendancesRoute,
  } as any)
const AuthenticatedTrainingPlansRegisterRoute =
  AuthenticatedTrainingPlansRegisterRouteImport.update({
    id: '/training-plans_/register',
    path: '/training-plans/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembersRegisterRoute =
  AuthenticatedMembersRegisterRouteImport.update({
    id: '/members_/register',
    path: '/members/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesRegisterRoute =
  AuthenticatedExercisesRegisterRouteImport.update({
    id: '/exercises_/register',
    path: '/exercises/register',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesGroupIdRoute =
  AuthenticatedExercisesGroupIdRouteImport.update({
    id: '/exercises_/$groupId',
    path: '/exercises/$groupId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembershipsRoute =
  AuthenticatedAdminMembershipsRouteImport.update({
    id: '/memberships',
    path: '/memberships',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSettingsIndexRoute =
  AuthenticatedAdminSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedTrainingPlansEditTrainingPlanIdRoute =
  AuthenticatedTrainingPlansEditTrainingPlanIdRouteImport.update({
    id: '/training-plans_/edit/$trainingPlanId',
    path: '/training-plans/edit/$trainingPlanId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembersUpdateMemberIdRoute =
  AuthenticatedMembersUpdateMemberIdRouteImport.update({
    id: '/members_/update/$memberId',
    path: '/members/update/$memberId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembersRegisterClinicalProfileRoute =
  AuthenticatedMembersRegisterClinicalProfileRouteImport.update({
    id: '/members_/register_/clinical-profile',
    path: '/members/register/clinical-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembersProfileMemberIdRoute =
  AuthenticatedMembersProfileMemberIdRouteImport.update({
    id: '/members_/profile/$memberId',
    path: '/members/profile/$memberId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMembersMemberIdClinicalProfileRoute =
  AuthenticatedMembersMemberIdClinicalProfileRouteImport.update({
    id: '/members_/$memberId/clinical-profile',
    path: '/members/$memberId/clinical-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRiskFlagsRoute =
  AuthenticatedAdminSettingsRiskFlagsRouteImport.update({
    id: '/risk-flags',
    path: '/risk-flags',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsParametersRoute =
  AuthenticatedAdminSettingsParametersRouteImport.update({
    id: '/parameters',
    path: '/parameters',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsGroupExercisesRoute =
  AuthenticatedAdminSettingsGroupExercisesRouteImport.update({
    id: '/group-exercises',
    path: '/group-exercises',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedExercisesGroupIdUpdateExerciseIdRoute =
  AuthenticatedExercisesGroupIdUpdateExerciseIdRouteImport.update({
    id: '/exercises_/$groupId_/update/$exerciseId',
    path: '/exercises/$groupId/update/$exerciseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesGroupIdProfileExerciseIdRoute =
  AuthenticatedExercisesGroupIdProfileExerciseIdRouteImport.update({
    id: '/exercises_/$groupId_/profile/$exerciseId',
    path: '/exercises/$groupId/profile/$exerciseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRiskFlagsRegisterRoute =
  AuthenticatedAdminSettingsRiskFlagsRegisterRouteImport.update({
    id: '/risk-flags_/register',
    path: '/risk-flags/register',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsGroupExercisesRegisterRoute =
  AuthenticatedAdminSettingsGroupExercisesRegisterRouteImport.update({
    id: '/group-exercises_/register',
    path: '/group-exercises/register',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute =
  AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRouteImport.update({
    id: '/risk-flags_/update/$riskFlagId',
    path: '/risk-flags/update/$riskFlagId',
    getParentRoute: () => AuthenticatedAdminSettingsRoute,
  } as any)
const AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute =
  AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRouteImport.update(
    {
      id: '/group-exercises_/update/$groupExerciseId',
      path: '/group-exercises/update/$groupExerciseId',
      getParentRoute: () => AuthenticatedAdminSettingsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/attendance': typeof AttendanceAttendanceRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/attendances': typeof AuthenticatedAttendancesRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/instructors': typeof AuthenticatedInstructorsRouteWithChildren
  '/members': typeof AuthenticatedMembersRouteWithChildren
  '/schedule': typeof AuthenticatedScheduleRoute
  '/training-plans': typeof AuthenticatedTrainingPlansRoute
  '/audit': typeof AuthenticatedAdminAuditRoute
  '/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/users': typeof AuthenticatedAdminUsersRoute
  '/exercises/$groupId': typeof AuthenticatedExercisesGroupIdRoute
  '/exercises/register': typeof AuthenticatedExercisesRegisterRoute
  '/members/register': typeof AuthenticatedMembersRegisterRoute
  '/training-plans/register': typeof AuthenticatedTrainingPlansRegisterRoute
  '/attendances/': typeof AuthenticatedAttendancesIndexRoute
  '/instructors/': typeof AuthenticatedInstructorsIndexRoute
  '/members/': typeof AuthenticatedMembersIndexRoute
  '/settings/group-exercises': typeof AuthenticatedAdminSettingsGroupExercisesRoute
  '/settings/parameters': typeof AuthenticatedAdminSettingsParametersRoute
  '/settings/risk-flags': typeof AuthenticatedAdminSettingsRiskFlagsRoute
  '/members/$memberId/clinical-profile': typeof AuthenticatedMembersMemberIdClinicalProfileRoute
  '/members/profile/$memberId': typeof AuthenticatedMembersProfileMemberIdRoute
  '/members/register/clinical-profile': typeof AuthenticatedMembersRegisterClinicalProfileRoute
  '/members/update/$memberId': typeof AuthenticatedMembersUpdateMemberIdRoute
  '/training-plans/edit/$trainingPlanId': typeof AuthenticatedTrainingPlansEditTrainingPlanIdRoute
  '/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/settings/group-exercises/register': typeof AuthenticatedAdminSettingsGroupExercisesRegisterRoute
  '/settings/risk-flags/register': typeof AuthenticatedAdminSettingsRiskFlagsRegisterRoute
  '/exercises/$groupId/profile/$exerciseId': typeof AuthenticatedExercisesGroupIdProfileExerciseIdRoute
  '/exercises/$groupId/update/$exerciseId': typeof AuthenticatedExercisesGroupIdUpdateExerciseIdRoute
  '/settings/group-exercises/update/$groupExerciseId': typeof AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute
  '/settings/risk-flags/update/$riskFlagId': typeof AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/attendance': typeof AttendanceAttendanceRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/training-plans': typeof AuthenticatedTrainingPlansRoute
  '/audit': typeof AuthenticatedAdminAuditRoute
  '/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/users': typeof AuthenticatedAdminUsersRoute
  '/exercises/$groupId': typeof AuthenticatedExercisesGroupIdRoute
  '/exercises/register': typeof AuthenticatedExercisesRegisterRoute
  '/members/register': typeof AuthenticatedMembersRegisterRoute
  '/training-plans/register': typeof AuthenticatedTrainingPlansRegisterRoute
  '/attendances': typeof AuthenticatedAttendancesIndexRoute
  '/instructors': typeof AuthenticatedInstructorsIndexRoute
  '/members': typeof AuthenticatedMembersIndexRoute
  '/settings/group-exercises': typeof AuthenticatedAdminSettingsGroupExercisesRoute
  '/settings/parameters': typeof AuthenticatedAdminSettingsParametersRoute
  '/settings/risk-flags': typeof AuthenticatedAdminSettingsRiskFlagsRoute
  '/members/$memberId/clinical-profile': typeof AuthenticatedMembersMemberIdClinicalProfileRoute
  '/members/profile/$memberId': typeof AuthenticatedMembersProfileMemberIdRoute
  '/members/register/clinical-profile': typeof AuthenticatedMembersRegisterClinicalProfileRoute
  '/members/update/$memberId': typeof AuthenticatedMembersUpdateMemberIdRoute
  '/training-plans/edit/$trainingPlanId': typeof AuthenticatedTrainingPlansEditTrainingPlanIdRoute
  '/settings': typeof AuthenticatedAdminSettingsIndexRoute
  '/settings/group-exercises/register': typeof AuthenticatedAdminSettingsGroupExercisesRegisterRoute
  '/settings/risk-flags/register': typeof AuthenticatedAdminSettingsRiskFlagsRegisterRoute
  '/exercises/$groupId/profile/$exerciseId': typeof AuthenticatedExercisesGroupIdProfileExerciseIdRoute
  '/exercises/$groupId/update/$exerciseId': typeof AuthenticatedExercisesGroupIdUpdateExerciseIdRoute
  '/settings/group-exercises/update/$groupExerciseId': typeof AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute
  '/settings/risk-flags/update/$riskFlagId': typeof AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_attendance': typeof AttendanceRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_attendance/attendance': typeof AttendanceAttendanceRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/attendances': typeof AuthenticatedAttendancesRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRoute
  '/_authenticated/instructors': typeof AuthenticatedInstructorsRouteWithChildren
  '/_authenticated/members': typeof AuthenticatedMembersRouteWithChildren
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/training-plans': typeof AuthenticatedTrainingPlansRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/_admin/memberships': typeof AuthenticatedAdminMembershipsRoute
  '/_authenticated/_admin/settings': typeof AuthenticatedAdminSettingsRouteWithChildren
  '/_authenticated/_admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/exercises_/$groupId': typeof AuthenticatedExercisesGroupIdRoute
  '/_authenticated/exercises_/register': typeof AuthenticatedExercisesRegisterRoute
  '/_authenticated/members_/register': typeof AuthenticatedMembersRegisterRoute
  '/_authenticated/training-plans_/register': typeof AuthenticatedTrainingPlansRegisterRoute
  '/_authenticated/attendances/': typeof AuthenticatedAttendancesIndexRoute
  '/_authenticated/instructors/': typeof AuthenticatedInstructorsIndexRoute
  '/_authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/_authenticated/_admin/settings/group-exercises': typeof AuthenticatedAdminSettingsGroupExercisesRoute
  '/_authenticated/_admin/settings/parameters': typeof AuthenticatedAdminSettingsParametersRoute
  '/_authenticated/_admin/settings/risk-flags': typeof AuthenticatedAdminSettingsRiskFlagsRoute
  '/_authenticated/members_/$memberId/clinical-profile': typeof AuthenticatedMembersMemberIdClinicalProfileRoute
  '/_authenticated/members_/profile/$memberId': typeof AuthenticatedMembersProfileMemberIdRoute
  '/_authenticated/members_/register_/clinical-profile': typeof AuthenticatedMembersRegisterClinicalProfileRoute
  '/_authenticated/members_/update/$memberId': typeof AuthenticatedMembersUpdateMemberIdRoute
  '/_authenticated/training-plans_/edit/$trainingPlanId': typeof AuthenticatedTrainingPlansEditTrainingPlanIdRoute
  '/_authenticated/_admin/settings/': typeof AuthenticatedAdminSettingsIndexRoute
  '/_authenticated/_admin/settings/group-exercises_/register': typeof AuthenticatedAdminSettingsGroupExercisesRegisterRoute
  '/_authenticated/_admin/settings/risk-flags_/register': typeof AuthenticatedAdminSettingsRiskFlagsRegisterRoute
  '/_authenticated/exercises_/$groupId_/profile/$exerciseId': typeof AuthenticatedExercisesGroupIdProfileExerciseIdRoute
  '/_authenticated/exercises_/$groupId_/update/$exerciseId': typeof AuthenticatedExercisesGroupIdUpdateExerciseIdRoute
  '/_authenticated/_admin/settings/group-exercises_/update/$groupExerciseId': typeof AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute
  '/_authenticated/_admin/settings/risk-flags_/update/$riskFlagId': typeof AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/forgot-password'
    | '/login'
    | '/attendances'
    | '/billing'
    | '/exercises'
    | '/instructors'
    | '/members'
    | '/schedule'
    | '/training-plans'
    | '/audit'
    | '/memberships'
    | '/settings'
    | '/users'
    | '/exercises/$groupId'
    | '/exercises/register'
    | '/members/register'
    | '/training-plans/register'
    | '/attendances/'
    | '/instructors/'
    | '/members/'
    | '/settings/group-exercises'
    | '/settings/parameters'
    | '/settings/risk-flags'
    | '/members/$memberId/clinical-profile'
    | '/members/profile/$memberId'
    | '/members/register/clinical-profile'
    | '/members/update/$memberId'
    | '/training-plans/edit/$trainingPlanId'
    | '/settings/'
    | '/settings/group-exercises/register'
    | '/settings/risk-flags/register'
    | '/exercises/$groupId/profile/$exerciseId'
    | '/exercises/$groupId/update/$exerciseId'
    | '/settings/group-exercises/update/$groupExerciseId'
    | '/settings/risk-flags/update/$riskFlagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/forgot-password'
    | '/login'
    | '/billing'
    | '/exercises'
    | '/schedule'
    | '/training-plans'
    | '/audit'
    | '/memberships'
    | '/users'
    | '/exercises/$groupId'
    | '/exercises/register'
    | '/members/register'
    | '/training-plans/register'
    | '/attendances'
    | '/instructors'
    | '/members'
    | '/settings/group-exercises'
    | '/settings/parameters'
    | '/settings/risk-flags'
    | '/members/$memberId/clinical-profile'
    | '/members/profile/$memberId'
    | '/members/register/clinical-profile'
    | '/members/update/$memberId'
    | '/training-plans/edit/$trainingPlanId'
    | '/settings'
    | '/settings/group-exercises/register'
    | '/settings/risk-flags/register'
    | '/exercises/$groupId/profile/$exerciseId'
    | '/exercises/$groupId/update/$exerciseId'
    | '/settings/group-exercises/update/$groupExerciseId'
    | '/settings/risk-flags/update/$riskFlagId'
  id:
    | '__root__'
    | '/_attendance'
    | '/_auth'
    | '/_authenticated'
    | '/_attendance/attendance'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_authenticated/_admin'
    | '/_authenticated/attendances'
    | '/_authenticated/billing'
    | '/_authenticated/exercises'
    | '/_authenticated/instructors'
    | '/_authenticated/members'
    | '/_authenticated/schedule'
    | '/_authenticated/training-plans'
    | '/_authenticated/'
    | '/_authenticated/_admin/audit'
    | '/_authenticated/_admin/memberships'
    | '/_authenticated/_admin/settings'
    | '/_authenticated/_admin/users'
    | '/_authenticated/exercises_/$groupId'
    | '/_authenticated/exercises_/register'
    | '/_authenticated/members_/register'
    | '/_authenticated/training-plans_/register'
    | '/_authenticated/attendances/'
    | '/_authenticated/instructors/'
    | '/_authenticated/members/'
    | '/_authenticated/_admin/settings/group-exercises'
    | '/_authenticated/_admin/settings/parameters'
    | '/_authenticated/_admin/settings/risk-flags'
    | '/_authenticated/members_/$memberId/clinical-profile'
    | '/_authenticated/members_/profile/$memberId'
    | '/_authenticated/members_/register_/clinical-profile'
    | '/_authenticated/members_/update/$memberId'
    | '/_authenticated/training-plans_/edit/$trainingPlanId'
    | '/_authenticated/_admin/settings/'
    | '/_authenticated/_admin/settings/group-exercises_/register'
    | '/_authenticated/_admin/settings/risk-flags_/register'
    | '/_authenticated/exercises_/$groupId_/profile/$exerciseId'
    | '/_authenticated/exercises_/$groupId_/update/$exerciseId'
    | '/_authenticated/_admin/settings/group-exercises_/update/$groupExerciseId'
    | '/_authenticated/_admin/settings/risk-flags_/update/$riskFlagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AttendanceRoute: typeof AttendanceRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_attendance': {
      id: '/_attendance'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/training-plans': {
      id: '/_authenticated/training-plans'
      path: '/training-plans'
      fullPath: '/training-plans'
      preLoaderRoute: typeof AuthenticatedTrainingPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructors': {
      id: '/_authenticated/instructors'
      path: '/instructors'
      fullPath: '/instructors'
      preLoaderRoute: typeof AuthenticatedInstructorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendances': {
      id: '/_authenticated/attendances'
      path: '/attendances'
      fullPath: '/attendances'
      preLoaderRoute: typeof AuthenticatedAttendancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_attendance/attendance': {
      id: '/_attendance/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceAttendanceRouteImport
      parentRoute: typeof AttendanceRoute
    }
    '/_authenticated/members/': {
      id: '/_authenticated/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedMembersRoute
    }
    '/_authenticated/instructors/': {
      id: '/_authenticated/instructors/'
      path: '/'
      fullPath: '/instructors/'
      preLoaderRoute: typeof AuthenticatedInstructorsIndexRouteImport
      parentRoute: typeof AuthenticatedInstructorsRoute
    }
    '/_authenticated/attendances/': {
      id: '/_authenticated/attendances/'
      path: '/'
      fullPath: '/attendances/'
      preLoaderRoute: typeof AuthenticatedAttendancesIndexRouteImport
      parentRoute: typeof AuthenticatedAttendancesRoute
    }
    '/_authenticated/training-plans_/register': {
      id: '/_authenticated/training-plans_/register'
      path: '/training-plans/register'
      fullPath: '/training-plans/register'
      preLoaderRoute: typeof AuthenticatedTrainingPlansRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members_/register': {
      id: '/_authenticated/members_/register'
      path: '/members/register'
      fullPath: '/members/register'
      preLoaderRoute: typeof AuthenticatedMembersRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises_/register': {
      id: '/_authenticated/exercises_/register'
      path: '/exercises/register'
      fullPath: '/exercises/register'
      preLoaderRoute: typeof AuthenticatedExercisesRegisterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises_/$groupId': {
      id: '/_authenticated/exercises_/$groupId'
      path: '/exercises/$groupId'
      fullPath: '/exercises/$groupId'
      preLoaderRoute: typeof AuthenticatedExercisesGroupIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/users': {
      id: '/_authenticated/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/settings': {
      id: '/_authenticated/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/memberships': {
      id: '/_authenticated/_admin/memberships'
      path: '/memberships'
      fullPath: '/memberships'
      preLoaderRoute: typeof AuthenticatedAdminMembershipsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/audit': {
      id: '/_authenticated/_admin/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/settings/': {
      id: '/_authenticated/_admin/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedAdminSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/training-plans_/edit/$trainingPlanId': {
      id: '/_authenticated/training-plans_/edit/$trainingPlanId'
      path: '/training-plans/edit/$trainingPlanId'
      fullPath: '/training-plans/edit/$trainingPlanId'
      preLoaderRoute: typeof AuthenticatedTrainingPlansEditTrainingPlanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members_/update/$memberId': {
      id: '/_authenticated/members_/update/$memberId'
      path: '/members/update/$memberId'
      fullPath: '/members/update/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersUpdateMemberIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members_/register_/clinical-profile': {
      id: '/_authenticated/members_/register_/clinical-profile'
      path: '/members/register/clinical-profile'
      fullPath: '/members/register/clinical-profile'
      preLoaderRoute: typeof AuthenticatedMembersRegisterClinicalProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members_/profile/$memberId': {
      id: '/_authenticated/members_/profile/$memberId'
      path: '/members/profile/$memberId'
      fullPath: '/members/profile/$memberId'
      preLoaderRoute: typeof AuthenticatedMembersProfileMemberIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members_/$memberId/clinical-profile': {
      id: '/_authenticated/members_/$memberId/clinical-profile'
      path: '/members/$memberId/clinical-profile'
      fullPath: '/members/$memberId/clinical-profile'
      preLoaderRoute: typeof AuthenticatedMembersMemberIdClinicalProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/settings/risk-flags': {
      id: '/_authenticated/_admin/settings/risk-flags'
      path: '/risk-flags'
      fullPath: '/settings/risk-flags'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRiskFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/_admin/settings/parameters': {
      id: '/_authenticated/_admin/settings/parameters'
      path: '/parameters'
      fullPath: '/settings/parameters'
      preLoaderRoute: typeof AuthenticatedAdminSettingsParametersRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/_admin/settings/group-exercises': {
      id: '/_authenticated/_admin/settings/group-exercises'
      path: '/group-exercises'
      fullPath: '/settings/group-exercises'
      preLoaderRoute: typeof AuthenticatedAdminSettingsGroupExercisesRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/exercises_/$groupId_/update/$exerciseId': {
      id: '/_authenticated/exercises_/$groupId_/update/$exerciseId'
      path: '/exercises/$groupId/update/$exerciseId'
      fullPath: '/exercises/$groupId/update/$exerciseId'
      preLoaderRoute: typeof AuthenticatedExercisesGroupIdUpdateExerciseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises_/$groupId_/profile/$exerciseId': {
      id: '/_authenticated/exercises_/$groupId_/profile/$exerciseId'
      path: '/exercises/$groupId/profile/$exerciseId'
      fullPath: '/exercises/$groupId/profile/$exerciseId'
      preLoaderRoute: typeof AuthenticatedExercisesGroupIdProfileExerciseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/settings/risk-flags_/register': {
      id: '/_authenticated/_admin/settings/risk-flags_/register'
      path: '/risk-flags/register'
      fullPath: '/settings/risk-flags/register'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRiskFlagsRegisterRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/_admin/settings/group-exercises_/register': {
      id: '/_authenticated/_admin/settings/group-exercises_/register'
      path: '/group-exercises/register'
      fullPath: '/settings/group-exercises/register'
      preLoaderRoute: typeof AuthenticatedAdminSettingsGroupExercisesRegisterRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/_admin/settings/risk-flags_/update/$riskFlagId': {
      id: '/_authenticated/_admin/settings/risk-flags_/update/$riskFlagId'
      path: '/risk-flags/update/$riskFlagId'
      fullPath: '/settings/risk-flags/update/$riskFlagId'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
    '/_authenticated/_admin/settings/group-exercises_/update/$groupExerciseId': {
      id: '/_authenticated/_admin/settings/group-exercises_/update/$groupExerciseId'
      path: '/group-exercises/update/$groupExerciseId'
      fullPath: '/settings/group-exercises/update/$groupExerciseId'
      preLoaderRoute: typeof AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRouteImport
      parentRoute: typeof AuthenticatedAdminSettingsRoute
    }
  }
}

interface AttendanceRouteChildren {
  AttendanceAttendanceRoute: typeof AttendanceAttendanceRoute
}

const AttendanceRouteChildren: AttendanceRouteChildren = {
  AttendanceAttendanceRoute: AttendanceAttendanceRoute,
}

const AttendanceRouteWithChildren = AttendanceRoute._addFileChildren(
  AttendanceRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedAdminSettingsRouteChildren {
  AuthenticatedAdminSettingsGroupExercisesRoute: typeof AuthenticatedAdminSettingsGroupExercisesRoute
  AuthenticatedAdminSettingsParametersRoute: typeof AuthenticatedAdminSettingsParametersRoute
  AuthenticatedAdminSettingsRiskFlagsRoute: typeof AuthenticatedAdminSettingsRiskFlagsRoute
  AuthenticatedAdminSettingsIndexRoute: typeof AuthenticatedAdminSettingsIndexRoute
  AuthenticatedAdminSettingsGroupExercisesRegisterRoute: typeof AuthenticatedAdminSettingsGroupExercisesRegisterRoute
  AuthenticatedAdminSettingsRiskFlagsRegisterRoute: typeof AuthenticatedAdminSettingsRiskFlagsRegisterRoute
  AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute: typeof AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute
  AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute: typeof AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute
}

const AuthenticatedAdminSettingsRouteChildren: AuthenticatedAdminSettingsRouteChildren =
  {
    AuthenticatedAdminSettingsGroupExercisesRoute:
      AuthenticatedAdminSettingsGroupExercisesRoute,
    AuthenticatedAdminSettingsParametersRoute:
      AuthenticatedAdminSettingsParametersRoute,
    AuthenticatedAdminSettingsRiskFlagsRoute:
      AuthenticatedAdminSettingsRiskFlagsRoute,
    AuthenticatedAdminSettingsIndexRoute: AuthenticatedAdminSettingsIndexRoute,
    AuthenticatedAdminSettingsGroupExercisesRegisterRoute:
      AuthenticatedAdminSettingsGroupExercisesRegisterRoute,
    AuthenticatedAdminSettingsRiskFlagsRegisterRoute:
      AuthenticatedAdminSettingsRiskFlagsRegisterRoute,
    AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute:
      AuthenticatedAdminSettingsGroupExercisesUpdateGroupExerciseIdRoute,
    AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute:
      AuthenticatedAdminSettingsRiskFlagsUpdateRiskFlagIdRoute,
  }

const AuthenticatedAdminSettingsRouteWithChildren =
  AuthenticatedAdminSettingsRoute._addFileChildren(
    AuthenticatedAdminSettingsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminMembershipsRoute: typeof AuthenticatedAdminMembershipsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminMembershipsRoute: AuthenticatedAdminMembershipsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAttendancesRouteChildren {
  AuthenticatedAttendancesIndexRoute: typeof AuthenticatedAttendancesIndexRoute
}

const AuthenticatedAttendancesRouteChildren: AuthenticatedAttendancesRouteChildren =
  {
    AuthenticatedAttendancesIndexRoute: AuthenticatedAttendancesIndexRoute,
  }

const AuthenticatedAttendancesRouteWithChildren =
  AuthenticatedAttendancesRoute._addFileChildren(
    AuthenticatedAttendancesRouteChildren,
  )

interface AuthenticatedInstructorsRouteChildren {
  AuthenticatedInstructorsIndexRoute: typeof AuthenticatedInstructorsIndexRoute
}

const AuthenticatedInstructorsRouteChildren: AuthenticatedInstructorsRouteChildren =
  {
    AuthenticatedInstructorsIndexRoute: AuthenticatedInstructorsIndexRoute,
  }

const AuthenticatedInstructorsRouteWithChildren =
  AuthenticatedInstructorsRoute._addFileChildren(
    AuthenticatedInstructorsRouteChildren,
  )

interface AuthenticatedMembersRouteChildren {
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
}

const AuthenticatedMembersRouteChildren: AuthenticatedMembersRouteChildren = {
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
}

const AuthenticatedMembersRouteWithChildren =
  AuthenticatedMembersRoute._addFileChildren(AuthenticatedMembersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAttendancesRoute: typeof AuthenticatedAttendancesRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRoute
  AuthenticatedInstructorsRoute: typeof AuthenticatedInstructorsRouteWithChildren
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRouteWithChildren
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedTrainingPlansRoute: typeof AuthenticatedTrainingPlansRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedExercisesGroupIdRoute: typeof AuthenticatedExercisesGroupIdRoute
  AuthenticatedExercisesRegisterRoute: typeof AuthenticatedExercisesRegisterRoute
  AuthenticatedMembersRegisterRoute: typeof AuthenticatedMembersRegisterRoute
  AuthenticatedTrainingPlansRegisterRoute: typeof AuthenticatedTrainingPlansRegisterRoute
  AuthenticatedMembersMemberIdClinicalProfileRoute: typeof AuthenticatedMembersMemberIdClinicalProfileRoute
  AuthenticatedMembersProfileMemberIdRoute: typeof AuthenticatedMembersProfileMemberIdRoute
  AuthenticatedMembersRegisterClinicalProfileRoute: typeof AuthenticatedMembersRegisterClinicalProfileRoute
  AuthenticatedMembersUpdateMemberIdRoute: typeof AuthenticatedMembersUpdateMemberIdRoute
  AuthenticatedTrainingPlansEditTrainingPlanIdRoute: typeof AuthenticatedTrainingPlansEditTrainingPlanIdRoute
  AuthenticatedExercisesGroupIdProfileExerciseIdRoute: typeof AuthenticatedExercisesGroupIdProfileExerciseIdRoute
  AuthenticatedExercisesGroupIdUpdateExerciseIdRoute: typeof AuthenticatedExercisesGroupIdUpdateExerciseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAttendancesRoute: AuthenticatedAttendancesRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRoute,
  AuthenticatedInstructorsRoute: AuthenticatedInstructorsRouteWithChildren,
  AuthenticatedMembersRoute: AuthenticatedMembersRouteWithChildren,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedTrainingPlansRoute: AuthenticatedTrainingPlansRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedExercisesGroupIdRoute: AuthenticatedExercisesGroupIdRoute,
  AuthenticatedExercisesRegisterRoute: AuthenticatedExercisesRegisterRoute,
  AuthenticatedMembersRegisterRoute: AuthenticatedMembersRegisterRoute,
  AuthenticatedTrainingPlansRegisterRoute:
    AuthenticatedTrainingPlansRegisterRoute,
  AuthenticatedMembersMemberIdClinicalProfileRoute:
    AuthenticatedMembersMemberIdClinicalProfileRoute,
  AuthenticatedMembersProfileMemberIdRoute:
    AuthenticatedMembersProfileMemberIdRoute,
  AuthenticatedMembersRegisterClinicalProfileRoute:
    AuthenticatedMembersRegisterClinicalProfileRoute,
  AuthenticatedMembersUpdateMemberIdRoute:
    AuthenticatedMembersUpdateMemberIdRoute,
  AuthenticatedTrainingPlansEditTrainingPlanIdRoute:
    AuthenticatedTrainingPlansEditTrainingPlanIdRoute,
  AuthenticatedExercisesGroupIdProfileExerciseIdRoute:
    AuthenticatedExercisesGroupIdProfileExerciseIdRoute,
  AuthenticatedExercisesGroupIdUpdateExerciseIdRoute:
    AuthenticatedExercisesGroupIdUpdateExerciseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AttendanceRoute: AttendanceRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
